#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_get_node_info_impl(
    port_: MessagePort,
    network_info: impl Wire2Api<NetworkInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "get_node_info",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_network_info = network_info.wire2api();
            move |task_callback| get_node_info(api_network_info)
        },
    )
}
fn wire_generate_mnemonic_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "generate_mnemonic",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Result::<_, ()>::Ok(generate_mnemonic()),
    )
}
fn wire_request_funds_impl(
    port_: MessagePort,
    network_info: impl Wire2Api<NetworkInfo> + UnwindSafe,
    wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "request_funds",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_network_info = network_info.wire2api();
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| request_funds(api_network_info, api_wallet_info)
        },
    )
}
fn wire_create_iota_account_impl(
    port_: MessagePort,
    network_info: impl Wire2Api<NetworkInfo> + UnwindSafe,
    wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "create_iota_account",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_network_info = network_info.wire2api();
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| create_iota_account(api_network_info, api_wallet_info)
        },
    )
}
fn wire_write_advanced_transaction_impl(
    port_: MessagePort,
    transaction_params: impl Wire2Api<TransactionParams> + UnwindSafe,
    wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "write_advanced_transaction",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_transaction_params = transaction_params.wire2api();
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| write_advanced_transaction(api_transaction_params, api_wallet_info)
        },
    )
}
fn wire_read_incoming_transactions_impl(
    port_: MessagePort,
    wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "read_incoming_transactions",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| read_incoming_transactions(api_wallet_info)
        },
    )
}
fn wire_read_outgoing_transactions_impl(
    port_: MessagePort,
    wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "read_outgoing_transactions",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| read_outgoing_transactions(api_wallet_info)
        },
    )
}
fn wire_get_balance_impl(port_: MessagePort, wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "get_balance",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| get_balance(api_wallet_info)
        },
    )
}
fn wire_get_addresses_impl(
    port_: MessagePort,
    wallet_info: impl Wire2Api<WalletInfo> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "get_addresses",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_wallet_info = wallet_info.wire2api();
            move |task_callback| get_addresses(api_wallet_info)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
#[path = "bridge_generated.web.rs"]
mod web;
#[cfg(target_family = "wasm")]
pub use self::web::*;

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use self::io::*;
