// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Rust {
  Future<String> getNodeInfo({required NetworkInfo networkInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetNodeInfoConstMeta;

  Future<String> generateMnemonic({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGenerateMnemonicConstMeta;

  Future<String> createWalletAccount(
      {required NetworkInfo networkInfo,
      required WalletInfo walletInfo,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateWalletAccountConstMeta;

  Future<String> getAddresses({required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetAddressesConstMeta;

  Future<String> createTransaction(
      {required WalletInfo walletInfo,
      required TransactionParams transactionParams,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateTransactionConstMeta;

  Future<String> createAdvancedTransaction(
      {required WalletInfo walletInfo,
      required TransactionParams transactionParams,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateAdvancedTransactionConstMeta;

  Future<String> generateAddress(
      {required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGenerateAddressConstMeta;

  Future<String> getSentTransactions(
      {required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetSentTransactionsConstMeta;

  Future<String> getReceivedTransactions(
      {required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetReceivedTransactionsConstMeta;

  Future<String> getSingleTransaction(
      {required WalletInfo walletInfo,
      required String transactionId,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetSingleTransactionConstMeta;

  Future<String> checkBalance({required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCheckBalanceConstMeta;

  Future<String> requestFunds(
      {required NetworkInfo networkInfo,
      required WalletInfo walletInfo,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRequestFundsConstMeta;

  Future<String> createDecentralizedIdentifier(
      {required NetworkInfo networkInfo,
      required WalletInfo walletInfo,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateDecentralizedIdentifierConstMeta;

  Future<String> binToHex(
      {required String val, required int len, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBinToHexConstMeta;

  Future<String> createIotaAccount(
      {required NetworkInfo networkInfo,
      required WalletInfo walletInfo,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateIotaAccountConstMeta;

  Future<String> writeAdvancedTransaction(
      {required TransactionParams transactionParams,
      required WalletInfo walletInfo,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWriteAdvancedTransactionConstMeta;

  Future<String> readIncomingTransactions(
      {required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReadIncomingTransactionsConstMeta;

  Future<String> readOutgoingTransactions(
      {required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReadOutgoingTransactionsConstMeta;

  Future<String> getBalance({required WalletInfo walletInfo, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetBalanceConstMeta;
}

class NetworkInfo {
  final String nodeUrl;
  final String faucetUrl;

  const NetworkInfo({
    required this.nodeUrl,
    required this.faucetUrl,
  });
}

class TransactionParams {
  final String transactionTag;
  final String transactionMetadata;
  final String receiverAddress;
  final String storageDepositReturnAddress;

  const TransactionParams({
    required this.transactionTag,
    required this.transactionMetadata,
    required this.receiverAddress,
    required this.storageDepositReturnAddress,
  });
}

class WalletInfo {
  final String alias;
  final String mnemonic;
  final String strongholdPassword;
  final String strongholdFilepath;
  final String lastAddress;

  const WalletInfo({
    required this.alias,
    required this.mnemonic,
    required this.strongholdPassword,
    required this.strongholdFilepath,
    required this.lastAddress,
  });
}
